version: '3.8'

services:
  api:
    build: .
    image: api-fast-food-customer
    container_name: api-fast-food-customer-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1