version: '3.8'

services:
  api:
    build: .
    image: api-fast-food-customer-image
    container_name: api-fast-food-customer-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1