apiVersion: v1
kind: Service
metadata:
  name: <repository-name>-service
spec:
  type: LoadBalancer
  selector:
    app: <repository-name>
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000