on:
  push:
    branches:
      - main

env:
  CLUSTER_NAME: "infra-tech-challenge"  # Nome do cluster EKS

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

  build-and-push-ecr:
    name: Build and Push Docker Image to AWS ECR
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Etapa 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Etapa 2: Configurar AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Etapa 3: Autenticar no Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

       # Etapa 4: Extrair o nome do repositório
      - name: Extract repository name
        id: repo-name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      # Etapa 5: Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t $REPO_NAME:latest .
          docker tag $REPO_NAME:latest ${{ steps.login-ecr.outputs.registry }}/$REPO_NAME:latest

      # Etapa 6: Enviar a imagem para o ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$REPO_NAME:latest

      # Etapa 7: Verificar se o EKS já foi criado
      - name: Check if EKS cluster exists
        run: |
          aws eks describe-cluster --name $CLUSTER_NAME --region ${{ secrets.AWS_REGION }} || exit 1
        continue-on-error: false  # Caso o cluster não exista, o workflow falha aqui

  kubernetes-deploy:
    name: Deploy Application to EKS
    runs-on: ubuntu-latest
    needs: build-and-push-ecr

    steps:
      # Etapa 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Etapa 2: Configurar AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Etapa 3: Configurar kubectl para interagir com o EKS
      - name: Configure kubectl
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name $CLUSTER_NAME

      # Etapa 4: Definir as variáveis de ambiente
      - name: Set environment variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      # Etapa 5: Substituir variáveis nos arquivos Kubernetes
      - name: Substitute variables in deployment.yaml
        run: |
          envsubst < k8s/deployment.yaml > k8s/deployment-final.yaml
          cat k8s/deployment-final.yaml

      - name: Substitute variables in service.yaml
        run: |
          envsubst < k8s/service.yaml > k8s/service-final.yaml
          cat k8s/service-final.yaml

      # Etapa 6: Aplicar Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment-final.yaml
          kubectl apply -f k8s/service-final.yaml

      # Etapa 7: Verificar o status do Deployment
      - name: Verify Deployment
        run: |
          kubectl get all